version: "3"

services:
    zookeeper:
        restart: always
        image: docker.io/bitnami/zookeeper:3.8
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - kafka-network

    kafka:
        container_name: kafka
        image: docker.io/bitnami/kafka:latest
        ports:
            - "9092:9092"
            - "9093:9093"
        environment:
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
            - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
            - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
        depends_on:
            - zookeeper
        networks:
            - kafka-network

    data-producer:
        build:
            context: ./
            dockerfile: data_producer.Dockerfile
        env_file: .env
        volumes:
            - ./code_search_net:/app/data/code_search_net
        depends_on:
            - kafka
        networks:
            - kafka-network

    data-processor:
        build:
            context: ./
            dockerfile: data_processor.Dockerfile
        env_file: .env
        depends_on:
            - kafka
        networks:
            - kafka-network

    ml-service:
        build:
            context: ./
            dockerfile: ml.Dockerfile
        env_file: .env
        depends_on:
            - kafka
        networks:
            - kafka-network

    data-post-processor:
        build:
            context: ./
            dockerfile: data_post_processor.Dockerfile
        env_file: .env
        depends_on:
            - kafka
        networks:
            - kafka-network

    visualization-service:
        build:
            context: ./
            dockerfile: visualization.Dockerfile
        env_file: .env
        depends_on:
            - kafka
        ports:
            - 8501:8501
        networks:
            - kafka-network

networks:
    kafka-network:
        driver: bridge
