KAFKA_URL = 'KAFKA_URL'
PRODUCED_RAW_DATA_TOPIC = 'PRODUCED_RAW_DATA_TOPIC'
PROCESSED_DATA_TOPIC = 'PROCESSED_DATA_TOPIC'
POST_PROCESSED_DATA_TOPIC = 'POST_PROCESSED_DATA_TOPIC'
ML_DATA_TOPIC = 'ML_DATA_TOPIC'
SLEEP_TIME = 'SLEEP_TIME'

DATA_PATH = "DATA_PATH"

CODE_NAMES = ["python", "javascript", "go", "java", "php", "ruby"]
ML_PROCESS = 'ML_PROCESS'  # 'random_sample' or 'codeberta'
